networks:
  duty_timer_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "192.168.1.0/24"

volumes:
  duty_timer_data: # Define the pgdata volume here

services:
  db:
    image: postgres:15-alpine
    volumes:
      - duty_timer_data:/var/lib/postgresql/duty_timer_data
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6Akshn21IKBO0622
      POSTGRES_DB: duty_timer
    ports:
      - "5432:5432"
    networks:
      - duty_timer_network

  server:
    build: .
    container_name: my_server
    environment:
      DATABASE_URL: "postgresql://postgres:6Akshn21IKBO0622@db:5432/duty_timer"
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "4000:4000"
      - "587:587"
    networks:
      - duty_timer_network
